name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}" >> $GITHUB_ENV

    - name: Install dependencies
      working-directory: ./backend
      run: NODE_OPTIONS="--max-old-space-size=512" npm ci

    - name: Compile the backend project
      working-directory: ./backend
      run: npm run compile

    - name: Stop and delete previous pm2 processes
      run: |
        pm2 stop backend || true
        pm2 delete backend || true

    - name: Start the backend using pm2
      working-directory: ./backend
      run: |
        pm2 start ./dist/src/index.js --name "backend" -- --port 3001
        pm2 save
