name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20.11.1"

    - name: Install dependencies and build
      working-directory: ./frontend
      run: |
        NODE_OPTIONS="--max-old-space-size=512" npm ci
        npm run build

    - name: Copy Frontend
      run: |
        rsync -av --delete --exclude='.htaccess' ./frontend/dist/ /var/www/html/project2/
